version: "3.9"
services:
    web:
        build: 
            context: .
            dockerfile: .\NameAndAddressAPI\Dockerfile
        ports:
            - "8000:80"
        depends_on:
            - db
    db:
        image: ravendb/ravendb
        ports:
            - "38888:38888"
            - "8080:8080"
        environment:
            - RAVEN_ARGS='--Setup.Mode=None'
            - RAVEN_Security_UnsecuredAccessAllowed='PrivateNetwork'