version: "3.9"
services:
    web:
        build: 
            context: .
            dockerfile: .\NameAndAddressAPI\Dockerfile
        ports:
            - "8000:80"
        environment:
            - ASPNETCORE_ENVIRONMENT=docker
        depends_on:
            - db
    db:
        image: ravendb/ravendb
        dns:
            - 8.8.8.8
            - 8.8.4.4
        ports:
            - "38888:38888"
            - "8080:8080"
            - "443:443"
        environment:
            - RAVEN_ARGS='--Setup.Mode=None'
            - RAVEN_Security_UnsecuredAccessAllowed='PrivateNetwork'
            - PUBLIC_SERVER_URL=http://localhost:8080
            - "RAVEN_PublicServerUrl=http://db:8080"